spring:
      #  配置数据源
  datasource:
    username:  root
    password:  134112+hhhbb.*Z
    url: jdbc:mysql://localhost:3306/acef?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 20
      max-wait-millis: 200

#自定义数据
#本机公网Ip地址
IpAddress: huangchaoweb.cn
 #文件保存根路径
filePath: /root/file/
