#设置环境（开发/生产）
spring:
  profiles:
    active: prd
#解决同时两个SpringBoot项目放在Tomcat下启动，第二个项目会报unable to register MBean
  jmx:
    enabled: false
  #配置视图解析器
  mvc:
    view:
      prefix:
      suffix: .html


#配置mybatis
mybatis:
  #配置映射文件路径
  mapper-locations: classpath:mapping/*.xml
  #配置实体类别名，就是dao层操作所需传入或输出的对象类前缀，简化书写
  type-aliases-package: com.huangchao.acef.entity

#配置pagehelper分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

#配置服务器端口号
#server:
#  port: 80
#  servlet:
#    #配置访问前缀
#    context-path: /acef

config:
  #配置cookie基准生存期（7天）
  survivalTime: 604800
  #请求所能携带的最大单个文件大小
  maxFileSize: 20MB
  #请求的最大大小
  maxRequestSize: 100MB

  #活动文章图片/海报保存路径,相对图片保存路径
  activityArticleImgPath: aaip/
  #普通文章图片保存路径,相对图片保存路径
  articleImgPath: aip/
  #报名表保存路径，相对根路径
  entryFormPath: ef/
  #友情链接图片保存路径，相对图片保存路径
  friendlyLinkPath: fl/
  #成员介绍图片存放路径，相对图片保存路径
  memberIntroductionPath: mi/
  #轮播图或协会介绍图
  SlideshowOrAssociationIntroductionPath: ssoai/
  #富文本图片
  richTextPath: rt/

  #默认语言
  defaultLanguage: Chinese
  #邮箱验证码法发送人邮箱
  fromEmail: 15766237659@163.com
  #系统发生错误接收邮箱
  errorEmail: 1711591690@qq.com
  #邮箱第三方登录授权码
  authorizationCode: 134112hhhbbbk

logging:
  level:
    root: info
    #tomcat连接时长
server:
  connectionTimeout: 420000