spring:
  #  配置数据源
  datasource:
    username:  root
    password:  134112+hhhbb.*Z
    url: jdbc:mysql://localhost:3306/acef?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    #Hikari连接池的设置
    hikari:
      minimum-idle: 5 #最小连接
      maximum-pool-size: 25 #最大连接
      auto-commit: true #自动提交
      idle-timeout: 30000 #最大空闲时长(30秒)
      pool-name: DatebookHikariCP #连接池名
      max-lifetime: 900000 #最大生命周期
      connection-timeout: 15000 #连接超时时间
      connection-test-query: SELECT 1 #心跳检测

#自定义数据
#本机公网Ip地址
IpAddress: localhost
#文件保存跟路径
filePath: E:/file/

