spring:
  #配置数据源
  datasource:
    username: root
    password: 134112+hhhbb.*Z
    url: jdbc:mysql://129.204.168.205:3306/acef?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    #Hikari连接池的设置
    hikari:
      minimum-idle: 5 #最小连接
      maximum-pool-size: 30 #最大连接
      auto-commit: false #自动提交
      idle-timeout: 30000 #最大空闲时长(30秒)
      pool-name: DatebookHikariCP #连接池名
      max-lifetime: 900000 #最大生命周期
      connection-timeout: 4500 #连接超时时间
      connection-test-query: SELECT 1 #心跳检测

#自定义数据
config:
  #文件保存根路径
  filePath: /usr/local/all_project_file/acef/
  #服务器资源访问前缀
  urlPrefix: http://huangchaoweb.cn/